---
title: Growth Mindset
author: Stephen Ruby
date: '2019-12-03'
slug: growth-mindset
categories: []
tags: []
subtitle: ''
summary: '"People believe that their most basic ablilties can be developed through dedication and hard work - brains and talent are just the starting point"'
authors: [Stephen Ruby]
lastmod: '2019-12-03T16:20:34-08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

  I will begin first with a quote I share with my student on day one from Confucius which is “I hear and I forget. I see and I remember. I do and I understand.” This simple quote summarizes my teaching philosophy. Teaching is not a matter of pouring knowledge from one mind into another as one pours water from one glass into another. It is more like one candle igniting another. Each candle burns with its own fuel. The teacher awakens a love for truth and beauty in the heart of a student after which the student moves forward with powerful interest under the gentle guidance of the teacher. This kind of teacher will inspire a love of learning, while so many currently instill a distaste for it through their ignorance and lack of delight in it. I take a lot of my teaching philosophy from the research on active vs passive learning. There is a lot of academic literature which shows how important it is for students to be active participants in the learning. The old pedagogy of lecturing has been shown to be ineffective. In my classroom I don’t lecture much at all. I try to keep my lecturing to modeling a few examples before allowing my students to do most of the work and discovery on their own. I am also a big fan of exploratory lessons in which students discover things on their own. One activity I do with my students around march fourteenth is I bring in various circular objects that my students will spend time measuring the circumference and diameter. I then have them divide the diameter by the circumference for the various objects they have and to record what they notice. Many of them will begin to see that they are getting the same answer of roughly 3.14 regardless of the size of the circular object. This will often result in a eureka moment for them where they begin to discover the constant pi and how all circles are similar in that the ratio of their circumference and diameter is the same. I also share the analogy of working out to learning with my students. I explain to them if they wanted to get faster or stronger they wouldn’t just watch me lift weights or run expecting to improve. If they want to get faster then they need to run and exert effort to improve. If they want to get stronger then they have to lift weights and stress their muscles. The same applies to the classroom in that if they want to learn the material they have to be doing the work and embrace the mental struggle that goes with that. 
	Your mind is a powerful thing. The narratives you tell yourself and the things you believe about yourself can either prevent change from happening or allow new skills to grow. The highest levels of performance are empowered by the deepest levels of belief. The idea behind growth mindset is something that single handedly saved my life. I was always a fairly weak student in high school. I was a firm believer at the time in a fixed mindset. I thought that if I couldn’t understand something right away then that just meant I was unable of ever understanding it. I failed algebra 2 twice in high school and was only given a passing grade my senior year since my teacher was tired of seeing me. I didn’t go to college right after school but instead worked a labor job at a local crematory where I would burn bodies for 12 hours a day. It was grueling and depressing work but at the time I thought that was all I was cut out for. I would have probably stayed at this job but my grandfather had gotten sick to the point my grandmother no longer could care for him. I decided to quit my job and live with my grandparents so I could help my grandmother take care of my ailing grandfather.(I have since done the same for my other grandfather during his passing. I think you mature as a human when you care for your relatives during their last moments. I will do the same for my parents one day and hope my children do the same for me.) It was during this time that I gained a new mindset that I had to make a change in my life. I removed all fear I had of failure and decided I would concentrate all my effort on school. I started attending fresno city college where I took mainly science and math courses. These were the courses I struggled with the most in high school but I knew that those were the classes I had to overcome if I wanted to be successful. Those classes were what told me as a child that I was not smart enough. I wanted to prove to myself that I could excel in these classes. I worked extremely hard and got help often when I was stuck. As I begun to see success in these classes I became fascinated with these subjects and learned to embrace the pain of mental struggle. I ended up graduating with honors in mathematics and also got a minor in chemistry. I also worked as a math and science tutor nearly full time my last 3 years of college so that I could help other students who were like me. This was my way of giving back to all the tutors who helped me when I was starting out. The idea here was that I had to first have the belief that I could learn math before I could begin to see success. The first step to success is to have that belief that you can improve through hard work. I think because I experienced the power of growth mindset first hand that I want to share it with everyone I know. My sister actually struggled even more than I did with math to the point she would break down crying in class due to the pain of frustration. I shared with her the same idea behind growth mindset and she was able to graduate with honors with an accounting degree and now works at a big four accounting firm. I want everyone to know how powerful belief can be. I have a growth mindset lesson every week for my students through Jo Boalers website youcubed. She has lessons on there under a week of inspirational math where the lessons are more engaging and creative. What I like most about these lessons is that every lesson has a growth mindset video associated with them, such making mistakes is ok or that speed is not important in math class. It encourages students to think deeply on certain subjects and to understand why things are behaving they way they do. I make sure to do pre tests and share with my students the growth they make during the lesson. I praise effort in my classroom to remind them that through that effort they will improve. My students are reminded that struggle is essential for understanding. The fact you struggle with math is a good thing and working on these problems will only benefit you in the long term. I have seen students at the beginning of the year giving up before they even attempt a problem now asking me for more difficult math problems. Many of my students are resistant to growth mindset. However, I will continue to push it onto my students since I know that once they have that belief in themselves that anything is possible for them. 